# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxSwiftDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxRealm'
  pod 'RxFeedback'
  pod 'Action'
  pod 'RxDataSources'
  pod 'RxRealmDataSources'

  target 'RxSwiftDemoTests' do
    inherit! :search_paths

    pod 'RxNimble'
    pod 'RxTest'

  end

end
